// app/api/download/route.ts

import { NextRequest, NextResponse } from "next/server"
import { getServerSession } from "next-auth"
import { authOptions } from "@/lib/auth"
import { db } from "@/lib/db"
import JSZip from "jszip"

export async function GET(req: NextRequest) {
    const session = await getServerSession(authOptions)
    if (!session?.user) {
        return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const projectId = req.nextUrl.searchParams.get("projectId")
    if (!projectId) {
        return NextResponse.json({ error: "Project ID required" }, { status: 400 })
    }

    // Get project and check ownership
    const project = await db.project.findFirst({
        where: { id: projectId, userId: session.user.id },
        include: { user: true },
    })

    if (!project) {
        return NextResponse.json({ error: "Project not found" }, { status: 404 })
    }

    // Check if user can download (paid plan only)
    if (project.user.plan === "FREE") {
        return NextResponse.json(
            { error: "Upgrade to Pro to download code" },
            { status: 403 }
        )
    }

    if (!project.code) {
        return NextResponse.json({ error: "No code generated yet" }, { status: 400 })
    }

    // Create ZIP file
    const zip = new JSZip()
    const files = project.code as Record<string, string>

    for (const [path, content] of Object.entries(files)) {
        zip.file(path, content)
    }

    // Add README
    zip.file(
        "README.md",
        `# ${project.name}

Generated by ForgeAI

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

## Database Setup

\`\`\`bash
npx prisma db push
npx prisma generate
\`\`\`

## Environment Variables

Copy \`.env.example\` to \`.env\` and fill in your values.
`
    )

    const zipBuffer = await zip.generateAsync({ type: "nodebuffer" })

    return new NextResponse(Buffer.from(zipBuffer), {
        headers: {
            "Content-Type": "application/zip",
            "Content-Disposition": `attachment; filename="${project.slug}.zip"`,
        },
    })
}
