import { Metadata } from "next"

export const metadata: Metadata = {
    title: "Terms of Service - MeganAi",
    description: "Terms of service for MeganAi",
}

export default function TermsPage() {
    return (
        <div className="container max-w-4xl py-12">
            <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>

            <div className="prose prose-slate dark:prose-invert max-w-none">
                <p className="text-muted-foreground">Last updated: December 2024</p>

                <h2>Acceptance of Terms</h2>
                <p>
                    By accessing and using MeganAi, you accept and agree to be bound by the terms and
                    provision of this agreement.
                </p>

                <h2>Use License</h2>
                <p>
                    MeganAi grants you a personal, non-transferable license to use our AI code generation
                    platform for your development projects.
                </p>

                <h2>Generated Code</h2>
                <ul>
                    <li>You own all rights to the code generated by MeganAi</li>
                    <li>Generated code is provided "as is" without warranty</li>
                    <li>You are responsible for reviewing and testing all generated code</li>
                    <li>We are not liable for any issues arising from generated code</li>
                </ul>

                <h2>Account Responsibilities</h2>
                <p>You are responsible for:</p>
                <ul>
                    <li>Maintaining the confidentiality of your account</li>
                    <li>All activities that occur under your account</li>
                    <li>Notifying us immediately of any unauthorized access</li>
                </ul>

                <h2>Prohibited Uses</h2>
                <p>You may not use MeganAi to:</p>
                <ul>
                    <li>Generate malicious or illegal code</li>
                    <li>Violate any applicable laws or regulations</li>
                    <li>Infringe on intellectual property rights</li>
                    <li>Abuse or overload our systems</li>
                </ul>

                <h2>Termination</h2>
                <p>
                    We reserve the right to terminate or suspend access to our service immediately,
                    without prior notice, for conduct that we believe violates these Terms.
                </p>

                <h2>Changes to Terms</h2>
                <p>
                    We reserve the right to modify these terms at any time. Continued use of the service
                    constitutes acceptance of modified terms.
                </p>

                <h2>Contact</h2>
                <p>
                    Questions about Terms of Service? Contact us at:{" "}
                    <a href="mailto:legal@meganai.dev" className="text-primary hover:underline">
                        legal@meganai.dev
                    </a>
                </p>
            </div>
        </div>
    )
}
