/**
 * Architect Agent
 * Uses Claude Opus for high-level app architecture and planning
 */

import { ModelRouter } from "../../ai/router"
import type { Artifact } from "../core"

export interface ArchitectPlan {
    appStructure: string
    components: string[]
    routes: string[]
    dataModels: string[]
    techStack: Record<string, string>
}

export class ArchitectAgent {
    private router: ModelRouter

    constructor(apiKeys: Record<string, string>) {
        this.router = new ModelRouter(apiKeys)
    }

    async analyze(userPrompt: string): Promise<{ plan: ArchitectPlan; artifacts: Artifact[] }> {
        const systemPrompt = `You are an expert software architect specializing in modern web applications.

Your task: Analyze the user's request and create a comprehensive technical plan.

Output Format (JSON):
{
  "appStructure": "Brief description of the overall architecture",
  "components": ["List of React components needed"],
  "routes": ["List of app routes/pages"],
  "dataModels": ["List of database entities"],
  "techStack": {
    "frontend": "Next.js 14 + TypeScript",
    "backend": "Next.js API Routes",
    "database": "Prisma + PostgreSQL",
    "styling": "Tailwind CSS",
    "auth": "NextAuth.js"
  }
}

Be specific and detailed. Think about:
- User authentication flows
- Data relationships
- Component hierarchy
- Route structure
- State management needs`

        const result = await this.router.route(
            "architecture-planning",
            `${systemPrompt}\n\nUser Request: ${userPrompt}\n\nProvide the technical plan in JSON format:`
        )

        // Parse the plan
        const plan = this.parsePlan(result.response)

        // Generate architecture document
        const artifacts: Artifact[] = [
            {
                type: "file",
                path: "ARCHITECTURE.md",
                content: this.generateArchitectureDoc(plan, userPrompt),
                language: "markdown"
            }
        ]

        return { plan, artifacts }
    }

    private parsePlan(response: string): ArchitectPlan {
        try {
            // Try to extract JSON from markdown code blocks
            const jsonMatch = response.match(/```(?:json)?\n([\s\S]*?)\n```/)
            const jsonStr = jsonMatch ? jsonMatch[1] : response
            return JSON.parse(jsonStr)
        } catch (error) {
            // Fallback to basic plan
            return {
                appStructure: "Full-stack web application",
                components: ["HomePage", "Dashboard", "AuthForm"],
                routes: ["/", "/dashboard", "/login"],
                dataModels: ["User"],
                techStack: {
                    frontend: "Next.js 14 + TypeScript",
                    backend: "Next.js API Routes",
                    database: "Prisma + PostgreSQL",
                    styling: "Tailwind CSS"
                }
            }
        }
    }

    private generateArchitectureDoc(plan: ArchitectPlan, userPrompt: string): string {
        return `# Application Architecture

## User Requirements
${userPrompt}

## Overview
${plan.appStructure}

## Tech Stack
${Object.entries(plan.techStack).map(([k, v]) => `- **${k}**: ${v}`).join('\n')}

## Components
${plan.components.map(c => `- ${c}`).join('\n')}

## Routes
${plan.routes.map(r => `- ${r}`).join('\n')}

## Data Models
${plan.dataModels.map(m => `- ${m}`).join('\n')}

## Generated by MeganAi Architect Agent
`
    }
}
