import JSZip from "jszip"
import type { Artifact } from "@/lib/orchestrator/core"

export async function generateProjectZip(artifacts: Artifact[], projectName: string = "meganai-project"): Promise<Blob> {
    const zip = new JSZip()

    // Add README
    zip.file("README.md", `# ${projectName}

Generated by MeganAi

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

## Project Structure

This project was automatically generated with:
- Next.js 14
- TypeScript
- Tailwind CSS
- Prisma (if backend included)

## Deploy

\`\`\`bash
npm run build
\`\`\`
`)

    // Add package.json
    zip.file("package.json", JSON.stringify({
        name: projectName,
        version: "1.0.0",
        private: true,
        scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start",
            lint: "next lint"
        },
        dependencies: {
            "next": "^14.0.0",
            "react": "^18.2.0",
            "react-dom": "^18.2.0",
            "typescript": "^5.0.0"
        },
        devDependencies: {
            "@types/node": "^20.0.0",
            "@types/react": "^18.2.0",
            "@types/react-dom": "^18.2.0",
            "tailwindcss": "^3.3.0",
            "autoprefixer": "^10.4.0",
            "postcss": "^8.4.0"
        }
    }, null, 2))

    // Add all generated artifacts
    artifacts.forEach(artifact => {
        zip.file(artifact.path, artifact.content)
    })

    // Generate ZIP blob
    const blob = await zip.generateAsync({ type: "blob" })
    return blob
}

export function downloadBlob(blob: Blob, filename: string) {
    const url = URL.createObjectURL(blob)
    const link = document.createElement("a")
    link.href = url
    link.download = filename
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
}
