/**
 * WebContainer Templates
 * Starter files for different frameworks with Tailwind CSS
 */

/**
 * Base Vite + React + Tailwind template
 */
export function getViteReactTemplate(appName: string = "my-app"): Record<string, string> {
  return {
    "package.json": JSON.stringify({
      name: appName.toLowerCase().replace(/\s+/g, "-"),
      private: true,
      version: "0.0.0",
      type: "module",
      scripts: {
        dev: "vite",
        build: "vite build",
        preview: "vite preview"
      },
      dependencies: {
        react: "^18.2.0",
        "react-dom": "^18.2.0",
        "lucide-react": "^0.294.0",
        "clsx": "^2.0.0"
      },
      devDependencies: {
        "@vitejs/plugin-react": "^4.2.1",
        vite: "^5.0.8",
        tailwindcss: "^3.4.0",
        postcss: "^8.4.32",
        autoprefixer: "^10.4.16"
      }
    }, null, 2),

    "vite.config.js": `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: {
    host: true,
    port: 5173
  }
})
`,

    "postcss.config.js": `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`,

    "tailwind.config.js": `/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
      },
    },
  },
  plugins: [],
}
`,

    "index.html": `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${appName}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`,

    "src/main.jsx": `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
`,

    "src/App.jsx": `import { useState } from 'react'

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900">
      <div className="container mx-auto px-4 py-16">
        <div className="text-center">
          <h1 className="text-5xl font-bold text-white mb-4 bg-gradient-to-r from-blue-400 to-purple-500 bg-clip-text text-transparent">
            🚀 ${appName}
          </h1>
          <p className="text-slate-300 text-lg mb-8">Generated by MeganAi</p>
          <div className="inline-block bg-white/10 backdrop-blur-lg rounded-2xl p-8 border border-white/20">
            <button 
              onClick={() => setCount(c => c + 1)}
              className="px-6 py-3 bg-gradient-to-r from-blue-500 to-purple-600 text-white font-semibold rounded-xl hover:shadow-lg hover:shadow-purple-500/25 transition-all duration-300 hover:-translate-y-0.5"
            >
              Count: {count}
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}

export default App
`,

    "src/index.css": `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  font-family: 'Inter', system-ui, -apple-system, sans-serif;
  line-height: 1.5;
  font-weight: 400;
  color-scheme: dark;
}

body {
  margin: 0;
  min-width: 320px;
  min-height: 100vh;
  background: linear-gradient(135deg, #0f172a 0%, #1e1b4b 50%, #0f172a 100%);
}

* {
  box-sizing: border-box;
}

/* Custom scrollbar */
::-webkit-scrollbar {
  width: 8px;
  height: 8px;
}

::-webkit-scrollbar-track {
  background: rgba(255, 255, 255, 0.1);
}

::-webkit-scrollbar-thumb {
  background: rgba(255, 255, 255, 0.2);
  border-radius: 4px;
}

::-webkit-scrollbar-thumb:hover {
  background: rgba(255, 255, 255, 0.3);
}
`
  }
}

/**
 * Merge generated files with template
 * Template provides the dev server setup, generated files add the actual app code
 */
export function mergeWithTemplate(
  generatedFiles: Record<string, string>,
  appName: string = "MeganAi App"
): Record<string, string> {
  const template = getViteReactTemplate(appName)

  // Check if generated files include package.json
  if (generatedFiles["package.json"]) {
    try {
      // Merge dependencies
      const genPkg = JSON.parse(generatedFiles["package.json"])
      const templatePkg = JSON.parse(template["package.json"])

      const merged = {
        ...templatePkg,
        name: genPkg.name || templatePkg.name,
        dependencies: {
          ...templatePkg.dependencies,
          ...(genPkg.dependencies || {})
        },
        devDependencies: {
          ...templatePkg.devDependencies,
          ...(genPkg.devDependencies || {})
        }
      }
      template["package.json"] = JSON.stringify(merged, null, 2)
    } catch {
      // Keep template package.json if parsing fails
    }
  }

  // Ensure CSS has Tailwind directives
  if (generatedFiles["src/index.css"] && !generatedFiles["src/index.css"].includes("@tailwind")) {
    generatedFiles["src/index.css"] = `@tailwind base;
@tailwind components;
@tailwind utilities;

${generatedFiles["src/index.css"]}`
  }

  // Merge files, preferring generated files over template
  // BUT keep template's config files
  const configFiles = ["vite.config.js", "postcss.config.js", "tailwind.config.js", "index.html"]
  const result = { ...template }

  for (const [path, content] of Object.entries(generatedFiles)) {
    if (!configFiles.includes(path)) {
      result[path] = content
    }
  }

  return result
}

/**
 * Convert Next.js-style files to Vite-compatible structure
 * This is a simplified conversion for preview purposes
 */
export function convertNextToVite(files: Record<string, string>): Record<string, string> {
  const converted: Record<string, string> = {}
  let mainPageContent = ""
  let globalStyles = ""

  for (const [path, content] of Object.entries(files)) {
    // Skip Next.js specific files and backend code
    if (
      path.includes("app/api/") ||
      path === "next.config.ts" ||
      path === "next.config.js" ||
      path.startsWith("prisma/") ||
      path === ".env.example" ||
      path === "ARCHITECTURE.md" ||
      path === "tailwind.config.ts"
    ) {
      continue
    }

    // Capture global styles
    if (path === "app/globals.css" || path === "styles/globals.css") {
      globalStyles = content
      continue
    }

    // Convert app/page.tsx to src/App.jsx
    if (path === "app/page.tsx" || path === "app/page.jsx") {
      mainPageContent = convertNextComponent(content, "App")
      converted["src/App.jsx"] = mainPageContent
      continue
    }

    // Skip layout.tsx - we handle this in the template
    if (path === "app/layout.tsx" || path === "app/layout.jsx") {
      continue
    }

    // Convert components to src/components
    if (path.startsWith("components/")) {
      const newPath = `src/${path.replace(/\.tsx$/, ".jsx").replace(/\.ts$/, ".js")}`
      converted[newPath] = convertNextComponent(content)
      continue
    }

    // Convert lib to src/lib
    if (path.startsWith("lib/")) {
      const newPath = `src/${path.replace(/\.tsx$/, ".jsx").replace(/\.ts$/, ".js")}`
      converted[newPath] = content
      continue
    }

    // Handle dashboard and other pages - just keep as components
    if (path.startsWith("app/") && (path.endsWith(".tsx") || path.endsWith(".jsx"))) {
      const componentName = path.split("/")[1] || "Page"
      const safeName = componentName.charAt(0).toUpperCase() + componentName.slice(1)
      const newPath = `src/pages/${safeName}.jsx`
      converted[newPath] = convertNextComponent(content, safeName)
      continue
    }
  }

  // Add global styles with Tailwind directives
  if (globalStyles) {
    if (!globalStyles.includes("@tailwind")) {
      globalStyles = `@tailwind base;
@tailwind components;
@tailwind utilities;

${globalStyles}`
    }
    converted["src/index.css"] = globalStyles
  }

  return converted
}

/**
 * Convert a Next.js component to plain React
 */
function convertNextComponent(content: string, componentName?: string): string {
  let result = content

  // Remove Next.js specific imports
  result = result
    .replace(/import\s+.*from\s+['"]next\/.*['"]\s*;?\n?/g, "")
    .replace(/import\s+.*from\s+['"]@\/components\/ui\/.*['"]\s*;?\n?/g, "")
    .replace(/'use client'\s*\n?/g, "")
    .replace(/"use client"\s*\n?/g, "")

  // Convert Next.js components to HTML equivalents
  result = result
    .replace(/<Link\s+href=/g, "<a href=")
    .replace(/<\/Link>/g, "</a>")
    .replace(/<Image\s/g, "<img ")

  // If componentName provided, ensure proper export
  if (componentName) {
    // Replace export default function X with function ComponentName
    result = result.replace(
      /export\s+default\s+function\s+\w+/g,
      `function ${componentName}`
    )

    // Add export default if not present
    if (!result.includes("export default")) {
      result += `\n\nexport default ${componentName}`
    }
  }

  return result
}
