/**
 * WebContainer Templates
 * Starter files for different frameworks
 */

/**
 * Base Vite + React template
 */
export function getViteReactTemplate(appName: string = "my-app"): Record<string, string> {
    return {
        "package.json": JSON.stringify({
            name: appName.toLowerCase().replace(/\s+/g, "-"),
            private: true,
            version: "0.0.0",
            type: "module",
            scripts: {
                dev: "vite",
                build: "vite build",
                preview: "vite preview"
            },
            dependencies: {
                react: "^18.2.0",
                "react-dom": "^18.2.0"
            },
            devDependencies: {
                "@vitejs/plugin-react": "^4.2.1",
                vite: "^5.0.8"
            }
        }, null, 2),

        "vite.config.js": `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: {
    host: true,
    port: 5173
  }
})
`,

        "index.html": `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${appName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`,

        "src/main.jsx": `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
`,

        "src/App.jsx": `import { useState } from 'react'

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="app">
      <h1>🚀 ${appName}</h1>
      <p>Generated by MeganAi</p>
      <div className="card">
        <button onClick={() => setCount(c => c + 1)}>
          Count: {count}
        </button>
      </div>
    </div>
  )
}

export default App
`,

        "src/index.css": `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
  min-height: 100vh;
  color: white;
}

.app {
  max-width: 800px;
  margin: 0 auto;
  padding: 2rem;
  text-align: center;
}

h1 {
  font-size: 3rem;
  margin-bottom: 1rem;
  background: linear-gradient(to right, #667eea, #764ba2);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}

.card {
  margin-top: 2rem;
  padding: 2rem;
  background: rgba(255, 255, 255, 0.05);
  border-radius: 1rem;
  backdrop-filter: blur(10px);
}

button {
  padding: 0.75rem 1.5rem;
  font-size: 1rem;
  border: none;
  border-radius: 0.5rem;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  cursor: pointer;
  transition: transform 0.2s, box-shadow 0.2s;
}

button:hover {
  transform: translateY(-2px);
  box-shadow: 0 10px 20px rgba(102, 126, 234, 0.3);
}
`
    }
}

/**
 * Merge generated files with template
 * Template provides the dev server setup, generated files add the actual app code
 */
export function mergeWithTemplate(
    generatedFiles: Record<string, string>,
    appName: string = "MeganAi App"
): Record<string, string> {
    const template = getViteReactTemplate(appName)

    // Check if generated files include package.json
    if (generatedFiles["package.json"]) {
        try {
            // Merge dependencies
            const genPkg = JSON.parse(generatedFiles["package.json"])
            const templatePkg = JSON.parse(template["package.json"])

            const merged = {
                ...templatePkg,
                name: genPkg.name || templatePkg.name,
                dependencies: {
                    ...templatePkg.dependencies,
                    ...(genPkg.dependencies || {})
                },
                devDependencies: {
                    ...templatePkg.devDependencies,
                    ...(genPkg.devDependencies || {})
                }
            }
            template["package.json"] = JSON.stringify(merged, null, 2)
        } catch {
            // Keep template package.json if parsing fails
        }
    }

    // Merge files, preferring generated files over template
    return {
        ...template,
        ...generatedFiles
    }
}

/**
 * Convert Next.js-style files to Vite-compatible structure
 * This is a simplified conversion for preview purposes
 */
export function convertNextToVite(files: Record<string, string>): Record<string, string> {
    const converted: Record<string, string> = {}

    for (const [path, content] of Object.entries(files)) {
        // Skip Next.js specific files
        if (path.includes("app/api/") || path === "next.config.ts" || path === "next.config.js") {
            continue
        }

        // Convert app/page.tsx to src/App.jsx
        if (path === "app/page.tsx" || path === "app/page.jsx") {
            // Simple conversion - remove Next.js specific imports
            let converted_content = content
                .replace(/export default function \w+\(/g, "function App(")
                .replace(/export default function/g, "function App")

            // Add export default
            if (!converted_content.includes("export default App")) {
                converted_content += "\n\nexport default App"
            }

            converted["src/App.jsx"] = converted_content
            continue
        }

        // Convert components to src/components
        if (path.startsWith("components/")) {
            converted[`src/${path}`] = content
            continue
        }

        // Convert lib to src/lib
        if (path.startsWith("lib/")) {
            converted[`src/${path}`] = content
            continue
        }

        // Copy styles
        if (path === "app/globals.css" || path === "styles/globals.css") {
            converted["src/index.css"] = content
            continue
        }

        // Keep other files as-is in src
        if (!path.startsWith("prisma/") && !path.startsWith("app/")) {
            converted[`src/${path}`] = content
        }
    }

    return converted
}
